## Para listas
– np.array

In [1]:
import numpy as np


In [2]:
# as vectors from lists
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b

print(c)

print(type(c))

c.shape

[ 4  8 11 14 18]
<class 'numpy.ndarray'>


(5,)

In [3]:
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]] # create a list
a = np.array(l) # convert a list to an array
print(a)

a.shape

print(a.dtype) # get type of an array

# or directly as matrix

M = np.array([[1, 2], [3, 4]])
M.shape

M.dtype


#only one type
M[0,0] = "hello"

M = np.array([[1, 2], [3, 4]], dtype=complex)
M


[[1 2 3]
 [3 6 9]
 [2 4 6]]
int32


ValueError: invalid literal for int() with base 10: 'hello'

In [6]:
print(a)

print(a[0]) # this is just like a list of lists

print(a[1, 2]) # arrays can be given comma separated indices

print(a[1, 1:3]) # and slices

print(a[:,1])

print(a)

print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]
[1 2 3]
9
[6 9]
[2 6 4]
[[1 2 3]
 [3 6 9]
 [2 4 6]]
[[1 2 3]
 [3 6 9]
 [2 4 6]]


In [8]:
#Generation functions

x = np.arange(0, 10, 1) # arguments: start, stop, step
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 10, 25)


array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [11]:
np.logspace(0, 10, 10, base=np.e)


array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [15]:
# a diagonal matrix
np.diag([1,2,3])

b = np.zeros(5)
print(b)

b.dtype

n = 1000
my_int_array = np.zeros(n,dtype=int)
my_int_array.dtype

c = np.ones((3,3))
c


[0. 0. 0. 0. 0.]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
d = np.arange(5) # just like range()
print(d)

d[1] = 9.7
print(d) # arrays keep their type even if elements changed

print(d*0.4) # operations create a new array, with new type

d = np.arange(5, dtype=float)
print(d)

np.arange(3, 7, 0.5) # arbitrary start, stop and step

[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]
[0. 1. 2. 3. 4.]


array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [8]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
print(x)

# random data
np.random.rand(5,5)


[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


array([[0.90201177, 0.24213055, 0.41450165, 0.33250242, 0.18137155],
       [0.89357526, 0.38974859, 0.42531704, 0.02390699, 0.35134865],
       [0.35935282, 0.09342434, 0.28149165, 0.63597227, 0.69464689],
       [0.16731757, 0.82616206, 0.56769372, 0.98573644, 0.20788476],
       [0.6786309 , 0.67332969, 0.09166435, 0.94957498, 0.01457012]])

In [9]:
os.system('head DeBilt.txt')

0
data = np.genfromtxt('DeBilt.txt‘, delimiter=',‘, skip_header=1)
data.shape


SyntaxError: invalid character '‘' (U+2018) (3002480483.py, line 4)

In [ ]:
M = np.random.rand(3,3)
M


np.save('saved-matrix.npy', M)
np.load('saved-matrix.npy’)



In [12]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print(c)

arr = np.arange(100, 200)
select = [5, 25, 50, 75, -5]
print(arr[select]) # can use integer lists as indices


arr = np.arange(10, 20).reshape((2,5))


[10.   21.7  25.6  27.55]
[105 125 150 175 195]


In [14]:
print(arr.sum())

print(arr.mean())

print(arr.std())

print(arr.max())

print(arr.min())


145
14.5
2.8722813232690143
19
10


In [15]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort() # acts on array itself
print(arr)

x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

print(x)


[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]


In [21]:
a = np.array([[1.0, 2.0], [4.0, 3.0]])
print(a)

a.transpose()
print(np.linalg.inv(a))


u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u


j = np.array([[0.0, -1.0], [1.0, 0.0]])
np.dot (j, j) # matrix product


[[1. 2.]
 [4. 3.]]
[[-0.6  0.4]
 [ 0.8 -0.2]]


array([[-1.,  0.],
       [ 0., -1.]])

In [23]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)

print(a + b)
print(a-b)
print(a * b)
print(b / a)
print(a % b)
print(b**a)

a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a)
print(b)
print(a + b)

a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a * a)

print(b * b)

print(a * b)


[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]
[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]]
[1. 9.]
[[-1.  6.]
 [-3. 12.]
 [-5. 18.]]
